### ISSUE TITLE
Binding issue on Dali

### ISSUE THREAD

**Issue by DonNabla** [XENONnT/utilix#117]
When submitting a script with utilix (current master branch) from dali using xenonnt-development.simg I got the following issue in my log.

```
running on dali022
[33mWARNING:[0m skipping mount of /scratch/midway3/maxime: no such file or directory
/.singularity.d/actions/exec: line 9: /dali/lgrandi/maxime/tmp/tmpo2j7mec9.sh: No such file or directory
Python script failed with exit code 127
```

Such an error was fixed in the past with #102  by moving the bind before the partition. But it was then changed again in #110. 
Moving the bind again in batchq.py solves the error. But I would like to ask first if it will not trigger conflict with other partition etc.. or if a different approach should be used.

**Comment by yuema137** [comment]
Thanks @DonNabla , let me look into it
