### ISSUE TITLE
 Is `MongoUploader` and `MongoDownloader` used?

### ISSUE THREAD

**Issue by dachengx** [XENONnT/utilix#136]
They seem to be important in utilix: https://github.com/XENONnT/utilix/blob/bffe28c2180e5ace627a18048cd47691436a1971/utilix/__init__.py#L17.

But they are not used in code space of XENONnT: https://github.com/search?q=org%3AXENONnT+MongoDownloader&type=code&p=1.

**Comment by yuema137** [comment]
@dachengx Thanks. See #138 
I have checked and think removing the implementation here is a good practice. That was probably a redundant definition at an early stage when people were testing.
