### ISSUE TITLE
caslake partition in batchq.submitjob utility

### ISSUE THREAD

**Issue by cecilia-ferrari** [XENONnT/utilix#74]
Ciao! :wave: 

I was using batchq.submit_job function to submit jobs on caslake partition. However it returns this error message 
```
File "submit_job.py", line 24, in <module>
    batchq.submit_job('python job.py', log=job_log, partition='caslake', qos='caslake', mem_per_cpu=1000, )
  File "/home/[...]/utilix/utilix/batchq.py", line 160, in submit_job
    os.makedirs(TMPDIR[partition], exist_ok=True)
KeyError: 'caslake'
```
since the 'caslake' key is not implemented for TMPDIR see [this line](https://github.com/XENONnT/utilix/blob/bb07096196359b6b46c4994492289b9b5fea945e/utilix/batchq.py#L42) for reference.
What about adding the caslake key? Do you think it is convenient to do so? 

Thanks! :cherry_blossom:

**Comment by FaroutYLq** [comment]
Thanks a lot Cecilia for spotting this! Would you please give a try for #75? Let me know if it solves the issue.
