### ISSUE TITLE
Tests are not working and potentiallly dangerous

### ISSUE THREAD

**Issue by jorana** [XENONnT/utilix#9]
The tests in utilix fail and are potentially dangerous if you run it with admin privileges as we are messing with rundocs / deleting adding stuff.

Also does not work since we have nT and 1T separated.

Finally, could we automate them?

**Comment by ershockley** [comment]
@jorana  sorry, what tests are you talking about?

**Comment by jorana** [comment]
https://github.com/XENONnT/utilix/tree/master/tests

Here is what is the output of
```bash
(strax) joran@DESKTOP-F4PI41P:~/utilix$ pytest &> example_ptyest.log 
```
https://gist.github.com/jorana/bbf9ea022d1e487409125e655c6dbbe2

**Comment by jorana** [comment]
The updates here:
https://github.com/XENONnT/utilix/blob/master/tests/test_update.py

Are potentially dangerous as they mess with the runs-database. Should not matter if one is not using an admin account but this then depends on your ini file.

**Comment by ershockley** [comment]
Ah right -- I had forgotten about these tests to be honest, thanks for pointing it out! They probably broke when we started using the nT collection instead of 1T. I will add it to my TODO list. 

I don't think these pose much of a security risk. All it is doing is adding a data entry to a run and then removing the exact same one. Everything goes through the runDB api so it is performed in a controlled way. This seems like a useful test to me. 

Can you maybe expand on what you feel the risk is?

**Comment by jorana** [comment]
I just wanted to point out that in principle, I think it's a bad idea to start adding/deleting stuff in the real runs database.

If one wants to test, I would prefer a different database, or at least another collection. Because, like now, some tests might not work. Someone starts tinkering with the tests to fix them. Then I run these tests with my credentials and all of a sudden I've performed operations on the runs database.

It's not that I say they are dangerous now but 'potentially'. Also, they won't work with readonly accounts (hopefully). You rightfully point out that this run number 2000 is fine to edit. 

Perhaps that's an even better operation to test (see that we _cannot_ edit the rundb).

**Comment by ershockley** [comment]
I can see what you're saying, but I think you're not considering the protection of the runDB API here. There are currently only 4 methods in utilix that attempt write actions on the database: `update_data`, `update_context_collection`, and their `delete` counterparts. Both of these require admin credentials for the runDB API that I discussed at the Team A meeting last week. These credentials are not the ones in the e.g. global config on midway.

Here's I think the worst-case scenario. A naive user (1) modifies the test script to select a run that we care about, (2) changes that test data dictionary into one that matches exactly an already-existing one, and (3) has the credentials to perform the update/delete. If those three stars aligned then it's possible that a single element of a data array could be removed that we don't want removed. But it's not possible to e.g. delete a document or some other unwanted write operation using the runDB API, if that's your concern. 

Anyway I don't feel too strongly; we can delete the test if you prefer. I think it is useful though, as these operations are the ones admix and outsource use for data management (and they need to modify the runDB for obvious reasons). Performing the test on another database/collection is not possible with the API at this time, and I'm not sure it's worth the effort just for a test.

**Comment by jorana** [comment]
OK, maybe you are right this is indeed perhaps overthinking it 👍  and I also did not consider the runDB API
