### ISSUE TITLE
Incorrect use of `os.path.expanduser` in batchq in TMPDIR["dali"]

### ISSUE THREAD

**Issue by Microwave-WYB** [XENONnT/utilix#90]
`os.path.expanduser` should be used with `~`. It expands the `~` symbol to the current user's home directory. However, in the current code:
```python
    "dali": os.path.expanduser(f"/dali/lgrandi/{USER}/tmp"),
```
The path is an absolute path, so `os.path.expanduser` will have no effect. This will not lead to errors but should be replaced with an f-string.

**Comment by yuema137** [comment]
Already fixed.
